package com.ewallet.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Immutable audit ledger entry for every balance-changing operation.
 *
 * Double-Entry Accounting Rationale:
 * Every transfer produces TWO transaction rows:
 *   1. TRANSFER  (sender wallet, amount deducted)
 *   2. RECEIVE   (receiver wallet, amount credited)
 * This creates a full audit trail — direct balance mutations are strictly
 * prohibited. The transactions table is append-only via @CreationTimestamp.
 *
 * Indexes:
 * - idx_tx_sender_wallet   — fast lookup of outgoing transactions
 * - idx_tx_receiver_wallet — fast lookup of incoming transactions
 * - idx_tx_ref_num         — unique reference lookup for idempotency checks
 */
@Entity
@Table(name = "transactions", indexes = {
    @Index(name = "idx_tx_sender_wallet", columnList = "sender_wallet_id"),
    @Index(name = "idx_tx_receiver_wallet", columnList = "receiver_wallet_id"),
    @Index(name = "idx_tx_ref_num", columnList = "reference_number")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Human-readable unique reference number (e.g., "TXN-20260624-A3F2K9").
     * Used for customer support, idempotency lookup, and external reporting.
     * Generated by the service layer — not auto-incremented.
     */
    @Column(name = "reference_number", unique = true, nullable = false, length = 20)
    private String referenceNumber;

    /**
     * The wallet that sent funds. Nullable for TOPUP operations
     * (money comes from an external source, not another wallet).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_wallet_id")
    private Wallet senderWallet;

    /**
     * The wallet that received funds. Nullable for WITHDRAW operations
     * (money leaves the system to an external destination).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receiver_wallet_id")
    private Wallet receiverWallet;

    /**
     * Transaction amount. Always positive in the ledger row;
     * the direction is encoded by the type field.
     * precision=19, scale=4 matches Wallet.balance.
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    /**
     * Categorises this ledger entry: TRANSFER, RECEIVE, TOPUP, or WITHDRAW.
     * Stored as a string in the DB via @Enumerated(EnumType.STRING)
     * so that adding new values does not break existing ordinal mappings.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TransactionType type;

    /**
     * Current lifecycle state: PENDING → SUCCESS or FAILED.
     * Stored as a string for the same forward-compatibility reason.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TransactionStatus status;

    /**
     * Optional human-readable description or memo for the transaction.
     */
    @Column(length = 255)
    private String description;

    /**
     * Immutable timestamp set once on creation.
     * This field never changes (updatable = false).
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
