mail.development-log-enabled=false
mail.from-address=${MAIL_FROM_ADDRESS}
spring.mail.host=${SES_SMTP_HOST}
spring.mail.port=${SES_SMTP_PORT:587}
spring.mail.username=${SES_SMTP_USERNAME}
spring.mail.password=${SES_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
management.endpoint.health.show-details=never
server.forward-headers-strategy=framework
